# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8473f9e52d931f2ab5ba74fabd21503bc09b4f7fcf05bc998b059253c22b79507e14022d22652e0a258fd3527f9a9a7ba6b465d52a2ffd4f50d9e12a7c791c09

test:
  secret_key_base: f8adabcd1b654fce27c008d75d16349d526261ab1cdaf43824e20a7b290554f557a56229ba4e0222fcdb6855cc98f12018f6ffa4ecb64c1c30d53ee3c3f102f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
